
[package]
name = "PrisonerDilemmaSimulator"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = {workspace = true}
fyrox-graph = "0.36.2"
rand = "0.9.2"

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
