
[package]
name = "prisoner_dilemma_simulator"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = {workspace = true}
rand = "0.9.2"

[features]
default = ["fyrox/default"]
dylib-engine = ["fyrox/dylib"]
