
[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
fyroxed_base = { workspace = true }
prisoner_dilemma_simulator = { path = "../game", optional = true }

[features]
default = ["prisoner_dilemma_simulator", "fyroxed_base/default"]
dylib = ["fyroxed_base/dylib_engine"]
