
[package]
name = "executor"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { workspace = true }
prisoner_dilemma_simulator = { path = "../game", optional = true }

[features]
default = ["prisoner_dilemma_simulator"]
dylib = ["fyrox/dylib"]
